#!/bin/bash

echo "=================================="
echo "Aurora Motors - Flask Application"
echo "=================================="
echo ""
echo "To run this application, follow these steps:"
echo ""
echo "1. Install Python dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "2. Set up environment variables:"
echo "   cp .env.example .env"
echo "   (Edit .env file with your settings)"
echo ""
echo "3. Initialize the database:"
echo "   python run.py init_db"
echo ""
echo "4. (Optional) Seed sample data:"
echo "   python run.py seed_db"
echo ""
echo "5. Start the application:"
echo "   python run.py"
echo ""
echo "The application will be available at http://localhost:5000"
echo ""
echo "Default admin credentials:"
echo "  Email: admin@auroramotors.com"
echo "  Password: admin123"
echo ""
echo "=================================="